// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  gömülüSidebar: [
    {
      type: 'autogenerated',
      dirName: 'gömülü',
    },
  ],
  yapayzekaSidebar: [
    {
      type: 'autogenerated',
      dirName: 'yapayzeka',
    },
  ],
  programlamaSidebar: [
    {
      type: 'autogenerated',
      dirName: 'programlama',
    },
  ],
  ArastirmaSidebar: [
    {
      type: 'autogenerated',
      dirName: 'araştırma',
    },
  ],
};

module.exports = sidebars;
